'use client';

import { useState } from "react";
import { pinJSON } from "../../../lib/nft/ipfs";
import { mintWithFee } from "../../../lib/nft/sdk";
import TxToast from "../common/TxToast";
import { DEFAULT_CHAIN } from "../../../lib/nft/chains";

type Eip1193Provider = {
  request: (args: { method: string; params?: unknown[] }) => Promise<unknown>;
};

export default function MintDialog({
  image,
  onMintedAction, // renamed for Next.js client rule compliance
}: {
  image: string;
  onMintedAction?: (tokenId: string) => void;
}) {
  const [name, setName] = useState("My AI NFT");
  const [desc, setDesc] = useState("Generated by GAD AI Studio");
  const [busy, setBusy] = useState(false);
  const [hash, setHash] = useState<string | null>(null);

  const handleMint = async () => {
    try {
      setBusy(true);
      const metadata = { name, description: desc, image };
      const { url } = await pinJSON(metadata);

      const eth = (window as unknown as { ethereum?: Eip1193Provider }).ethereum;
      if (!eth) throw new Error("No EVM provider (window.ethereum) found");
      const accs = (await eth.request({ method: "eth_accounts" })) as unknown;
      const addr =
        Array.isArray(accs) && typeof accs[0] === "string" ? (accs[0] as string) : "";

      if (!addr) throw new Error("No connected account");

      const tx = await mintWithFee(addr, url);
      setHash(tx?.hash || null);
      alert("NFT minted!");
      onMintedAction?.("new");
    } catch (e: unknown) {
      console.error(e);
      const message =
        e instanceof Error
          ? e.message
          : typeof e === "object" && e !== null && "message" in e
          ? String((e as { message?: unknown }).message)
          : "Mint failed";
      alert(message);
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="border rounded p-3 mt-4 bg-[#0E0E12]/80 text-white">
      <div className="font-semibold text-lg mb-2">Mint Generated NFT</div>
      <input
        className="border rounded px-3 py-2 w-full bg-transparent mb-2"
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder="Name"
      />
      <textarea
        className="border rounded px-3 py-2 w-full bg-transparent mb-2"
        rows={3}
        value={desc}
        onChange={(e) => setDesc(e.target.value)}
        placeholder="Description"
      />
      <button
        onClick={handleMint}
        disabled={busy}
        className="border border-gold-500 text-gold-300 rounded px-4 py-2 hover:bg-gold-500 hover:text-black transition w-full"
      >
        {busy ? "Minting…" : "Mint to Wallet"}
      </button>
      <TxToast
        hash={hash}
        explorerBase={DEFAULT_CHAIN.explorer}
        onClose={() => setHash(null)}
      />
    </div>
  );
}
